### ISSUE TITLE
clicked

### ISSUE THREAD

**Issue by vicApakau** [toorshia/justgage#179]
how do I do clicked, and find out what I clicked?

I store my Gaugs in an array, as I don't know how many are there in DB.

**Comment by toorshia** [comment]
Sorry, I didn't understand you. Can you explain it a bit better?

**Comment by puppetMaster3** [comment]
I get a list oI fixed it by wrapping

**Comment by puppetMaster3** [comment]
I get a list of rows from DB, don't know how many rows.
So I have to create 'gags' dynamic. And I need to know what one got clicked. 
I solved, via div wrapper. I click on div.  So closed.

Also, I had a lot of problems that I can't explain, somehow it would not render. I wish you'd switch to snap svg instead of raphael.

**Comment by puppetMaster3** [comment]
thx for a nice project.

**Comment by toorshia** [comment]
Great :) Thanks! I'm actually planning to switch to snap very soon :)
