### ISSUE TITLE
Can I pass the dom element instead of passing id?

### ISSUE THREAD

**Issue by elgs** [toorshia/justgage#189]
In the examples, `id` of a div is passed to `JustGage`. Is it possible to avoid using id, and to pass the dom element itself to `JustGage`? Thanks.

**Comment by elgs** [comment]
Looking into the source code, is `parentNode` a div dom that I can pass in?

**Comment by toorshia** [comment]
From readme.md :)  

parentNode - use instead of id, attaches gauge to node which is outside of DOM tree - demo at http://justgage.com/examples/custom-node.html
- width - force gauge width
- height - force gauge height

This option was developed specifically for nodes outside of DOM tree, but I guess it will work fine for those inside the tree, as well :)

**Comment by elgs** [comment]
Thank. I'm wrapping it in Angular.js. My code looks like this, and it work well:

```js
app.directive('myChart', function () {
    return {
        restrict: "E",
        link: function (scope, element, attrs) {
            new JustGage({
                parentNode: $(element)[0],
                value: 67,
                min: 0,
                max: 100,
                title: "Visitors",
                label: "woo"
            });
        }
    }
});
```
