### ISSUE TITLE
Gauge not appearing in firefox, Edge and Chrome  53.0.2785.89 m

### ISSUE THREAD

**Issue by swatisucharita** [toorshia/justgage#244]
The SVG path does not appear in firefox and Edge.
It appears in chrome 52 version, after upgrading to chrome 53, it does not appear

**Comment by bunjiboys** [comment]
I have the same problem and I tracked it down to being because of the `<base href="/">` tag in my `<head>`. If I set the `base href` to an empty value or simply remove it entirely the graphs draw just fine, but if I set it to anything non-zero it the paths disappear.

This is obviously a problem since using AngularJS in HTML5 mode requires you to set `base href` to work properly.

Example HTML that breaks for me
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>GageTest</title>
    <base href="/">
</head>
<body>
<div id="gage"></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.4/raphael-min.js"></script>
<script src="justgage-1.2.2.min.js"></script>
<script> $(function() { var gage = new JustGage({id: 'gage',value: 67,min: 0,max: 100,title: 'Visitor'}) }); </script>
</body>
</html>
```

**Comment by bunjiboys** [comment]
I just submitted a pull-request (see #245) that should fix this, fairly simple fix.
