### ISSUE TITLE
Problem Color with CustomSectors

### ISSUE THREAD

**Issue by mxgr59** [toorshia/justgage#289]
When I define a "color" on the range of customSectors, nothing change, the color default stay

maybe I forgot an option ?

examples/custom-sectors.html

**Comment by andremacola** [comment]
Yes, same problem here.

**Comment by rjlyon** [comment]
I managed to fix this by using a local copy of justgage.js and changing line 1014 from:
`if (custSec.length > 0) {`
to:
`if (custSec.ranges.length > 0) {`

**Comment by qublibjohnny** [comment]
same issue here, it's always red no matter what colour I set

**Comment by tyrex1975** [comment]
Yep, same problem here too.

Rather than modifying JustGage (I'm using a CDN and prefer not to customise public libraries), just add a 'length' property to your customSectors object, and JustGage will find your color ranges:

`
customSectors: {
length: true, // Circumvent JustGage bug
ranges: [{
color: '#00FF00',
lo: 0,
hi: 100
}]
}
`

**Comment by qublibjohnny** [comment]
Thanks that worked!

**Comment by DaltonHarvey** [comment]
Good morning guys... sorry my ingles is not so good, but i have a question: how can I change my gauge color I'm using pentaho CDE, please can someone help m? 
I realy dont know how to do that

**Comment by robertsLando** [comment]
Fixed in latest released

**Comment by grreeenn** [comment]
@robertsLando but not on CDN, apperently

**Comment by robertsLando** [comment]
@grreeenn How to update on CDN?
